name: Code Scanning

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  flake8-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Run flake8 Linter
      run: |
        pip install flake8
        flake8 --count --show-source --statistics
